const MAJORS=[['Deli','yeni başlangıçlar, güven','☉'],['Büyücü','irade, beceri, odak','✦'],['Başrahibe','sezgi, iç ses, gizem','☾'],['İmparatoriçe','bereket, bakım, yaratım','❀'],['İmparator','yapı, sınırlar, otorite','♜'],['Aziz','değerler, rehberlik, gelenek','⌁'],['Aşıklar','uyum, seçim, bağ','♡'],['Savaş Arabası','kararlılık, yön, hareket','➳'],['Güç','şefkat, cesaret, sabır','♌'],['Ermiş','içe dönüş, arayış, ışık','☿'],['Kader Çarkı','döngü, değişim, fırsat','◌'],['Adalet','denge, gerçek, sorumluluk','⚖'],['Asılan Adam','bakış açısı, teslimiyet, bekleme','⌇'],['Ölüm','dönüşüm, kapanış, yenilenme','♇'],['Denge','uyum, ölçü, akış','⚗'],['Şeytan','bağlılıklar, gölge, özgürleşme','⛓'],['Kule','uyanış, kırılma, açıklık','⚡'],['Yıldız','umut, iyileşme, ilham','✧'],['Ay','belirsizlik, duygular, sezgi','☽'],['Güneş','canlılık, açıklık, neşe','☀'],['Mahkeme','farkındalık, çağrı, değerlendirme','◉'],['Dünya','tamamlanma, bütünlük, ustalık','◎']];
const SUITS=[['Asalar','eylem ve ilham','♨'],['Kupalar','duygu ve ilişki','♢'],['Kılıçlar','düşünce ve iletişim','†'],['Tılsımlar','kaynaklar ve somut adımlar','◈']];
const RANKS=['As','İki','Üç','Dört','Beş','Altı','Yedi','Sekiz','Dokuz','On','Prens','Şövalye','Kraliçe','Kral'];
const tarotCards=[...MAJORS.map((x,i)=>({id:`m${i}`,name:x[0],keywords:x[1],icon:x[2],meaning:`${x[1]} teması, bulunduğu konuma dikkatle yaklaşmayı öneriyor.`})),...SUITS.flatMap(([s,theme,icon],si)=>RANKS.map((r,i)=>({id:`${si}-${i}`,name:`${r} ${s}`,keywords:theme,icon,meaning:`${theme} alanında ${r.toLowerCase()} enerjisi öne çıkıyor.`})))] ;
const spreads=[
 {id:'single',name:'Tek Kart',count:1,desc:'Hızlı rehberlik ve günün ana enerjisi.',positions:['Odak noktası']},
 {id:'three',name:'Üç Kart',count:3,desc:'Durumun katmanlarını netleştirmek için.',positions:['Geçmişin izi','Şimdiki enerji','Yönelim']},
 {id:'choice',name:'Seçim Açılımı',count:4,desc:'İki yolun dinamiğini karşılaştırmak için.',positions:['Seçenek A','Seçenek B','Görünmeyen etken','Sana ait pusula']},
 {id:'relationship',name:'İlişki Açılımı',count:5,desc:'İki kişi arasındaki bağı görmek için.',positions:['Senin enerjin','Diğer kişinin enerjisi','Bağın kalbi','Gerilim alanı','Potansiyel']},
 {id:'horseshoe',name:'At Nalı',count:7,desc:'Bir konunun gelişimini okumak için.',positions:['Geçmiş','Şimdi','Yakın dinamik','Rehberlik','Dış etki','Umut/korku','Yönelim']},
 {id:'celtic',name:'Kelt Haçı',count:10,desc:'Kapsamlı ve katmanlı inceleme için.',positions:['Şimdi','Zorluk','Kök','Geçmiş','Olasılık','Yakın gelecek','Tutum','Çevre','Umut/korku','Sonuç eğilimi']}
];
let state={question:'',analysis:null,spread:null,cards:[],birth:null};
const $=s=>document.querySelector(s);const el=(tag,cls,txt)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(txt)x.textContent=txt;return x};
async function api(path,payload){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('API');return response.json()}
function show(id){document.querySelectorAll('.step').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function analyze(q){const t=q.toLocaleLowerCase('tr');const relationship=/ilişki|sevgili|aşk|eş|partner|o bana|aramız/.test(t);const career=/iş|kariyer|teklif|çalış|meslek|patron/.test(t);const finance=/para|yatırım|borç|finans/.test(t);const sensitive=/ölüm|intihar|kendime zarar|hamile|hastalık|dava|mahkeme/.test(t);const decision=/malı mıyım|mi yoksa|veya|ya da|seç|kabul/.test(t);const exact=/kesin|tam olarak|hangi tarihte|saat kaçta|yarın/.test(t);let category=relationship?'İlişki':career?'Kariyer':finance?'Maddi konular':'Kişisel yönelim';let spread=relationship?'relationship':decision?'choice':q.length>140?'three':'single';return {category,relationship,decision,sensitive,exact,spread,topic:career?'iş değişikliği':relationship?'ilişki dinamiği':finance?'maddi karar':'kişisel netlik'}}
function renderSpreads(){const grid=$('#spreadGrid');grid.innerHTML='';spreads.forEach(s=>{const b=el('button','spread-choice'+(s.id===state.analysis.spread?' selected recommended':''));b.type='button';b.dataset.id=s.id;b.innerHTML=`<b>${s.name}</b><span>${s.desc}</span>`;b.onclick=()=>{state.spread=s;document.querySelectorAll('.spread-choice').forEach(x=>x.classList.toggle('selected',x===b));$('#confirmSpread').innerHTML=`${s.name} ile devam et <span>→</span>`};grid.append(b)});state.spread=spreads.find(s=>s.id===state.analysis.spread)}
$('#question').addEventListener('input',e=>$('#charCount').textContent=`${e.target.value.length} / 500`);
$('#questionForm').addEventListener('submit',async e=>{e.preventDefault();state.question=$('#question').value.trim();state.analysis=analyze(state.question);try{const remote=await api('/api/question/analyze',{question:state.question});state.analysis={...state.analysis,spread:remote.recommendedSpread,decision:remote.hasMultipleOptions,relationship:remote.personCount===2,sensitive:remote.sensitive,exact:Boolean(remote.qualitySuggestion)}}catch{}const a=state.analysis;$('#analysisTags').innerHTML='';[a.category,a.decision?'Karar sorusu':'Açık uçlu soru',a.relationship?'İki kişili bağ':'Tekil bağlam'].forEach(t=>$('#analysisTags').append(el('span','',t)));$('#qualityMessage').textContent=a.sensitive?'Bu hassas bir konu olabilir. Yorum, güvenli düşünme alanı sunacak; uzman desteğinin yerini tutmayacak.':a.exact?'Sorun kesin bir gelecek sonucu istiyor olabilir. Açılımı olasılıkları ve kendi etki alanını görmek için kullanabilirsin.':'';$('#spreadReason').textContent=`“${a.topic}” bağlamındaki sorunun yapısı için ${spreads.find(s=>s.id===a.spread).name} daha anlamlı bir çerçeve sunabilir.`;renderSpreads();show('spreadStep')});
$('#confirmSpread').onclick=()=>show('birthStep');document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));
$('#hasPartner').onchange=e=>$('#partnerFields').classList.toggle('hidden',!e.target.checked);
$('#birthForm').addEventListener('submit',async e=>{e.preventDefault();state.birth={date:$('#birthDate').value,time:$('#birthTime').value,place:$('#birthPlace').value,partner:$('#hasPartner').checked};state.astrology=null;try{state.astrology=await api('/api/astrology/birth-chart',{birth:state.birth})}catch{}$('#drawInstruction').textContent=`${state.spread.name} için ${state.spread.count} kapalı kart seç. Kartın adı ve düz/ters yönü seçiminin ardından rastgele belirlenir.`;state.cards=[];renderSelection();show('drawStep')});
async function selectClosedCard(){if(state.cards.length>=state.spread.count)return;let available=tarotCards.filter(c=>!state.cards.some(x=>x.card.id===c.id)),card=available[randomIndex(available.length)],reversed=randomIndex(2)===0;try{const remote=await api('/api/tarot/draw',{count:1,usedIds:state.cards.map(x=>tarotCards.indexOf(x.card))});card=tarotCards[remote.drawn[0].index];reversed=remote.drawn[0].reversed}catch{}state.cards.push({card,reversed,position:state.spread.positions[state.cards.length]});renderSelection()}
function renderSelection(){const selected=$('#drawnCards'),library=$('#cardLibrary');selected.innerHTML='';library.innerHTML='';$('#selectionCount').textContent=`${state.cards.length} / ${state.spread.count} kart açıldı`;$('#completeSelection').disabled=state.cards.length!==state.spread.count;state.cards.forEach(drawn=>{const box=el('article','revealed-card'+(drawn.reversed?' reversed':''));box.innerHTML=`<div class="position">${drawn.position}</div><div class="card-icon">${drawn.card.icon}</div><strong>${drawn.card.name}</strong><small>${drawn.reversed?'TERS':'DÜZ'}</small>`;selected.append(box)});for(let index=0;index<78;index++){const button=el('button','library-card');button.type='button';button.disabled=state.cards.length>=state.spread.count;button.innerHTML=`<span class="library-icon">✦</span><span class="library-name">Kapalı kart ${index+1}</span>`;button.onclick=selectClosedCard;library.append(button)}}
function randomIndex(max){const bound=0x100000000-(0x100000000%max);const bytes=new Uint32Array(1);do{crypto.getRandomValues(bytes)}while(bytes[0]>=bound);return bytes[0]%max}
async function draw(){if(state.cards.length>=state.spread.count)return;const button=$('#drawCard');button.disabled=true;let available=tarotCards.filter(c=>!state.cards.some(x=>x.card.id===c.id));let card=available[randomIndex(available.length)],reversed=randomIndex(2)===0;try{const remote=await api('/api/tarot/draw',{count:1,usedIds:state.cards.map(x=>tarotCards.indexOf(x.card))});card=tarotCards[remote.drawn[0].index];reversed=remote.drawn[0].reversed}catch{}let drawn={card,reversed,position:state.spread.positions[state.cards.length]};state.cards.push(drawn);const box=el('article','revealed-card'+(reversed?' reversed':''));box.innerHTML=`<div class="position">${drawn.position}</div><div class="card-icon">${card.icon}</div><strong>${card.name}</strong><small>${reversed?'TERS':'DÜZ'}</small>`;$('#drawnCards').append(box);renderProgress();if(state.cards.length===state.spread.count){button.style.opacity='.35';setTimeout(renderResults,650)}else button.disabled=false}
$('#completeSelection').onclick=renderResults;
function sunSign(date){const month=Number(date.slice(5,7)),day=Number(date.slice(8));const signs=['Oğlak','Kova','Balık','Koç','Boğa','İkizler','Yengeç','Aslan','Başak','Terazi','Akrep','Yay'];const starts=[20,19,21,20,21,21,23,23,23,23,22,22];return signs[day>=starts[month-1]?month%12:month-1]}
function renderResults(){const a=state.analysis,sign=sunSign(state.birth.date),first=state.cards[0],names=state.cards.map(x=>x.card.name).join(', '),profile=$('#astroProfile'),ascendant=state.astrology?.data?.ascendant?.sign||state.astrology?.data?.ascendant||null;$('#resultQuestion').textContent=`“${state.question}”`;$('#generalResult').textContent=`Bu açılımda senin seçtiğin kartlar ${a.topic} konusuna iki aşamalı bakıyor: önce ${first.card.keywords.split(',')[0]} duygusunu fark etmeyi, ardından kararını kendi değerlerinle kontrol etmeyi öneriyor. Burada amaç tek bir cevap bulmak değil; sana iyi gelecek yolu daha sakin ve görünür kılmak.`;$('#tarotResult').innerHTML='';state.cards.forEach(x=>{const d=el('div');const direction=x.reversed?'Ters konum, bu temanın bastırılmış ya da yeniden ele alınması gereken tarafına işaret ediyor.':'Düz konum, bu temanın şu anda erişebildiğin yapıcı tarafını gösteriyor.';d.innerHTML=`<b>${x.position} — ${x.card.name} (${x.reversed?'ters':'düz'})</b><br>${direction} ${x.card.meaning}`;$('#tarotResult').append(d)});profile.innerHTML=`<span>Güneş: ${sign}</span>${ascendant?`<span>Yükselen: ${ascendant}</span>`:state.birth.time?'<span>Yükselen: doğrulanmış hesaplama bekliyor</span>':'<span>Yükselen için doğum saati gerekli</span>'}`;$('#astroResult').textContent=ascendant?`${sign} Güneş burcun ve ${ascendant} yükselenin, kartların vurguladığı ${first.card.keywords.split(',')[0]} temasını hem iç motivasyonların hem de dünyaya yaklaşımın açısından düşünmeyi öneriyor.`:`${sign} Güneş burcu, bu konuyu ele alırken anlam ve tutarlılık arayışını öne çıkarır. Yükselen; doğum saati, yerin koordinatları ve güvenilir ephemeris verisi olmadan hesaplanmaz. Bu nedenle doğrulanmış bir veri sağlayıcısı bağlı olmadıkça burada tahmini bir yükselen yorumu yapılmaz.`;$('#themesResult').textContent=`Kartların ortak noktası ${state.cards.slice(0,2).map(x=>x.card.keywords.split(',')[0]).join(' ve ')}. Bu, dışarıdaki tek bir işarete tutunmak yerine kendi sınırlarını, ihtiyacını ve sonraki küçük adımını belirlemenin daha faydalı olacağını söylüyor.`;$('#reflectionResult').textContent=`“Bu kararın içinde, kendi sesimi daha net duymam için hangi bilgiye ya da sınıra ihtiyacım var?”`;$('#whyResult').textContent=`Yorum; sorunun ${a.category.toLowerCase()} bağlamı, seçtiğin ${state.spread.name}, kartlara verdiğin pozisyon ve düz/ters yön tercihlerin ile doğum tarihinden hesaplanan ${sign} Güneş burcu temelinde oluşturuldu. Kartlar rastgele atanmadı; her birini sen seçtin.`;show('resultStep')}
$('#restart').onclick=()=>{state={question:'',analysis:null,spread:null,cards:[],birth:null};$('#questionForm').reset();$('#charCount').textContent='0 / 500';show('welcomeStep')};
