const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');
const { randomInt } = require('node:crypto');
const root = __dirname, port = Number(process.env.PORT || 3000), requests = new Map();
const MAX_BODY=32000, WINDOW=900000, LIMIT=25;
const spreads=[{id:'single',count:1},{id:'three',count:3},{id:'choice',count:4},{id:'relationship',count:5},{id:'horseshoe',count:7},{id:'celtic',count:10}];
function analysis(question){const q=question.toLocaleLowerCase('tr'),relation=/ilişki|sevgili|aşk|eş|partner|aramız/.test(q),career=/iş|kariyer|teklif|çalış|meslek|patron/.test(q),finance=/para|yatırım|borç|finans/.test(q),decision=/malı mıyım|mi yoksa|veya|ya da|seç|kabul/.test(q);return{category:relation?'relationship':career?'career':finance?'finance':'personal',questionType:decision?'decision':'exploration',personCount:relation?2:1,hasMultipleOptions:decision,sensitive:/ölüm|intihar|kendime zarar|hamile|hastalık|dava|mahkeme/.test(q),qualitySuggestion:/kesin|hangi tarihte|saat kaçta|yarın/.test(q)?'Kesin gelecek sonucu yerine seçeneklerinizi ve etki alanınızı inceleyen açık uçlu bir yaklaşım daha yararlı olabilir.':null,recommendedSpread:relation?'relationship':decision?'choice':question.length>140?'three':'single'}}
function send(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(body))}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>MAX_BODY)throw Error('SIZE')}try{return JSON.parse(text||'{}')}catch{throw Error('JSON')}}
function allowed(ip){const now=Date.now(),active=(requests.get(ip)||[]).filter(t=>now-t<WINDOW);if(active.length>=LIMIT)return false;active.push(now);requests.set(ip,active);return true}
function validBirth(b){return b&&/^\d{4}-\d{2}-\d{2}$/.test(b.date||'')&&typeof b.place==='string'&&b.place.trim().length>1}
async function astrology(input){if(!validBirth(input.birth))return[400,{error:'INVALID_BIRTH_DATA',message:'Geçerli bir doğum tarihi ve yeri girin.'}];if(!process.env.ASTROLOGY_API_URL)return[503,{error:'ASTROLOGY_NOT_CONFIGURED',message:'Doğrulanmış astroloji veri sağlayıcısı henüz yapılandırılmadı.'}];const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);try{const r=await fetch(process.env.ASTROLOGY_API_URL,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.ASTROLOGY_API_KEY?{Authorization:`Bearer ${process.env.ASTROLOGY_API_KEY}`}:{})},body:JSON.stringify(input),signal:c.signal});if(!r.ok)throw Error();return[200,{source:'verified-provider',data:await r.json()}]}catch{return[502,{error:'ASTROLOGY_UNAVAILABLE',message:'Astroloji verisi şu an alınamadı.'}]}finally{clearTimeout(timer)}}
async function interpret(input){if(typeof input.question!=='string'||input.question.trim().length<8||!Array.isArray(input.cards)||!input.cards.length)return[400,{error:'INVALID_INTERPRETATION_INPUT',message:'Yorum için soru ve kartlar gereklidir.'}];if(!process.env.OPENAI_API_KEY)return[503,{error:'AI_NOT_CONFIGURED',message:'Yorumlama servisi henüz yapılandırılmadı.'}];const instructions='Türkçe yaz. Tarot ve astrolojiyi sadece kişisel farkındalık/eğlence çerçevesinde yorumla. Kesin gelecek tahmini, tıbbi/hukuki/finansal yönlendirme, korkutucu veya manipülatif söylem kullanma. Astroloji verisi yoksa bunu açıkça belirt. Sadece sağlanan verileri kullan. general, tarot, astrology, themes, reflection, why alanları olan JSON döndür.';const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5',instructions,input:JSON.stringify(input),text:{format:{type:'json_object'}},store:false,max_output_tokens:1000}),signal:c.signal});if(!r.ok)throw Error();const data=await r.json();return[200,{interpretation:JSON.parse(data.output_text)}]}catch{return[502,{error:'AI_UNAVAILABLE',message:'Yorumlama servisi şu an yanıt veremiyor.'}]}finally{clearTimeout(timer)}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'};
http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`),ip=req.socket.remoteAddress||'unknown';if(url.pathname.startsWith('/api/')&&!allowed(ip))return send(res,429,{error:'RATE_LIMITED',message:'Çok fazla istek yapıldı. Lütfen biraz sonra tekrar deneyin.'});try{if(req.method==='GET'&&url.pathname==='/api/spreads')return send(res,200,{spreads});if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{status:'ok',services:{ai:Boolean(process.env.OPENAI_API_KEY),astrology:Boolean(process.env.ASTROLOGY_API_URL)}});if(req.method==='POST'&&url.pathname==='/api/question/analyze'){const x=await body(req);if(typeof x.question!=='string'||x.question.trim().length<8||x.question.length>500)return send(res,400,{error:'INVALID_QUESTION',message:'Soru 8–500 karakter olmalıdır.'});return send(res,200,analysis(x.question))}if(req.method==='POST'&&url.pathname==='/api/tarot/draw'){const x=await body(req),count=Number(x.count),used=Array.isArray(x.usedIds)?x.usedIds:[];if(!Number.isInteger(count)||count<1||count>10)return send(res,400,{error:'INVALID_DRAW',message:'Kart sayısı 1–10 arasında olmalıdır.'});const ids=Array.from({length:78},(_,i)=>i).filter(i=>!used.includes(i));if(ids.length<count)return send(res,400,{error:'INVALID_DRAW',message:'Aynı kart tekrar seçilemez.'});const drawn=[];while(drawn.length<count){const at=randomInt(ids.length);drawn.push({index:ids.splice(at,1)[0],reversed:randomInt(2)===0})}return send(res,200,{drawn})}if(req.method==='POST'&&url.pathname==='/api/astrology/birth-chart'){const [s,o]=await astrology(await body(req));return send(res,s,o)}if(req.method==='POST'&&url.pathname==='/api/interpretation'){const [s,o]=await interpret(await body(req));return send(res,s,o)}if(req.method!=='GET')return send(res,404,{error:'NOT_FOUND'});const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root))return send(res,403,{error:'FORBIDDEN'});const content=await fs.readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(content)}catch(e){send(res,e.message==='SIZE'?413:400,{error:'BAD_REQUEST',message:'İstek işlenemedi.'})}}).listen(port,()=>console.log(`Lunae is running at http://localhost:${port}`));
